version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn -B clean package -DskipTests
      - JAR=$(ls target/*.jar | head -n 1)
      - cp "$JAR" application.jar
artifacts:
  files:
    - application.jar
  discard-paths: yes
